name: Sample

on: 
  workflow_dispatch:
    inputs:
      commit_message:
        description: 'sample input'
        required: true

jobs:
  print_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Get commit safe
        env:
          COMMIT_MESSAGE: ${{ github.event.inputs.commit_message }}
        run: | 
          echo "$COMMIT_MESSAGE"

      - name: Get commit unsafe
        run: | 
          echo "${{ github.event.inputs.commit_message }}"

