name: Dangerous Workflow

on:
  pull_request_target:
    branches:
      - main

jobs:
  dangerouse_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: action/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
      - name: Run script
        run: /scripts/run-tests.sh